
--  1
SELECT *
FROM `BD101_AUTEURS`
ORDER BY `Nom`;

--  2
SELECT MIN(`BD101_EMPRUNTS`.`DateEmprunt`)
FROM `BD101_EMPRUNTS`;

--  3
SELECT MAX(`BD101_EMPRUNTS`.`DateEmprunt`)
FROM `BD101_EMPRUNTS`;

--  4
SELECT `BD101_AUTEURS`.`Nom`, `BD101_AUTEURS`.`Prenom`
FROM `BD101_AUTEURS`
INNER JOIN `BD101_LIVRES` USING(`IdAuteur`);

--  5
SELECT Nom, Prenom, Titre, BD101_EMPRUNTS.`IdExemplaire`
FROM `BD101_PERSONNES`
INNER JOIN `BD101_EMPRUNTS` USING (`IdPersonne`)
INNER JOIN `BD101_EXEMPLAIRES` ON `BD101_EMPRUNTS`.`IdExemplaire` = `BD101_EXEMPLAIRES`.`IdExemplaire` AND BD101_EMPRUNTS.`IdLivre` = `BD101_EXEMPLAIRES`.`IdLivre`
INNER JOIN `BD101_LIVRES` ON `BD101_EMPRUNTS`.`IdLivre` = `BD101_LIVRES`.`IdLivre`
ORDER BY `Nom`;

--  6
SELECT `BD101_EXEMPLAIRES`.`IdExemplaire`, `BD101_LIVRES`.`Titre`, `BD101_EXEMPLAIRES`.`Etat`
FROM `BD101_EXEMPLAIRES`
INNER JOIN `BD101_LIVRES` USING (`IdLivre`)
ORDER BY `Titre`, `IdExemplaire`;

--  7
SELECT `BD101_PERSONNES`.`Nom`, `BD101_PERSONNES`.`Prenom`, COUNT(BD101_EMPRUNTS.`IdExemplaire`)
FROM `BD101_PERSONNES`
INNER JOIN `BD101_EMPRUNTS` USING (`IdPersonne`)
GROUP BY `BD101_PERSONNES`.`IdPersonne`;

--  8
SELECT `BD101_LIVRES`.`Annee`
FROM `BD101_LIVRES`
WHERE `BD101_LIVRES`.`Titre` = UPPER("UN ROMAN RUSSE");

--  9
SELECT `BD101_LIVRES`.`Titre`
FROM `BD101_PERSONNES`
INNER JOIN `BD101_EMPRUNTS` USING (`IdPersonne`)
INNER JOIN `BD101_LIVRES` ON BD101_EMPRUNTS.`IdLivre` = `BD101_LIVRES`.`IdLivre`
WHERE `BD101_PERSONNES`.`Nom` = UPPER("FOURNIER") AND `BD101_PERSONNES`.`Prenom` = UPPER("ALEXIS");

--  10
SELECT `BD101_PERSONNES`.`Nom`, `BD101_PERSONNES`.`Prenom`, `BD101_LIVRES`.`Titre`
FROM `BD101_PERSONNES`
INNER JOIN `BD101_EMPRUNTS` USING (`IdPersonne`)
INNER JOIN `BD101_LIVRES` ON BD101_EMPRUNTS.`IdLivre` = `BD101_LIVRES`.`IdLivre`;

-- 11
SELECT `Titre`
FROM `BD101_LIVRES`
ORDER BY `Titre`;

-- 12
SELECT DISTINCT `Titre`
FROM `BD101_EMPRUNTS`
INNER JOIN `BD101_LIVRES` USING (`IdLivre`)
WHERE DateEmprunt BETWEEN '2000-01-01' AND '2000-12-31';

-- 13
SELECT `BD101_EMPRUNTS`.`DateEmprunt`, `BD101_EMPRUNTS`.`DateRetour`
FROM `BD101_EMPRUNTS`
INNER JOIN `BD101_LIVRES` USING (`IdLivre`)
WHERE BD101_LIVRES.`Titre` = UPPER('SUR LA TERRE COMME AU CIEL');

-- 14
SELECT `BD101_AUTEURS`.`Nom`
FROM `BD101_AUTEURS`
WHERE `Nom` LIKE 'G_____';

-- 15
SELECT Titre, COUNT(IdExemplaire)
FROM `BD101_LIVRES`
INNER JOIN `BD101_EXEMPLAIRES` USING (`IdLivre`)
GROUP BY `IdLivre`
ORDER BY `Titre`;

-- 16
SELECT `BD101_PERSONNES`.`Nom`, `BD101_PERSONNES`.`Prenom`, `Titre`
FROM `BD101_LIVRES`
INNER JOIN `BD101_EMPRUNTS` USING (`IdLivre`)
INNER JOIN `BD101_PERSONNES` ON BD101_EMPRUNTS.`IdPersonne` = `BD101_PERSONNES`.`IdPersonne`
WHERE `DateRetour` >= `DateEmprunt` + 21;

-- 17
SELECT Titre
FROM `BD101_LIVRES`
INNER JOIN `BD101_EMPRUNTS` USING (`IdLivre`)
GROUP BY `IdLivre`
HAVING COUNT(`IdLivre`) > 3;

-- 18
SELECT `BD101_EMPRUNTS`.`DateEmprunt`
FROM `BD101_EMPRUNTS`
INNER JOIN `BD101_LIVRES` USING (`IdLivre`)
WHERE `Titre` = UPPER("Rimbaud le fils")
ORDER BY `DateEmprunt` DESC;

-- 19
SELECT DateEmprunt, COUNT(DateEmprunt)
FROM BD101_EMPRUNTS
GROUP BY `DateEmprunt`;

-- 20
SELECT `Titre`, `BD101_AUTEURS`.`Nom`, `BD101_AUTEURS`.`Prenom`
FROM `BD101_EMPRUNTS`
INNER JOIN `BD101_LIVRES` USING(`IdLivre`)
INNER JOIN `BD101_AUTEURS` ON  BD101_LIVRES.`IdAuteur` = BD101_AUTEURS.`IdAuteur`
INNER JOIN `BD101_PERSONNES` USING(`IdPersonne`)
WHERE BD101_PERSONNES.`Nom` = UPPER('FOURNIER') AND BD101_PERSONNES.`Prenom` = UPPER('ALEXIS');

-- 21
SELECT Titre, COUNT(IdPersonne)
FROM `BD101_EMPRUNTS`
INNER JOIN `BD101_LIVRES` USING (`IdLivre`)
INNER JOIN `BD101_PERSONNES` USING (`IdPersonne`)
GROUP BY `IdLivre`;

-- 22
SELECT Etat
FROM `BD101_LIVRES`
INNER JOIN `BD101_EXEMPLAIRES` USING (`IdLivre`)
WHERE `IdLivre` = 12;

-- 23
SELECT DISTINCT BD101_PERSONNES.*
FROM `BD101_PERSONNES`
INNER JOIN `BD101_EMPRUNTS` USING (`IdPersonne`)
WHERE `DateRetour` > `DateEmprunt` + 10;

-- 24
SELECT `BD101_AUTEURS`.`Nom`, `BD101_AUTEURS`.`Prenom`, COUNT(IdLivre)
FROM `BD101_AUTEURS`
INNER JOIN `BD101_LIVRES` USING (`IdAuteur`)
GROUP BY `IdAuteur`;

-- 25
SELECT `BD101_AUTEURS`.`Nom`, `BD101_AUTEURS`.`Prenom`
FROM `BD101_AUTEURS`
INNER JOIN `BD101_LIVRES` USING (`IdAuteur`)
GROUP BY `IdAuteur`
HAVING COUNT(`IdLivre`) > 2;

-- 26
SELECT COUNT(IdLivre) AS NbLivres
FROM `BD101_LIVRES`
WHERE `Annee` BETWEEN '1995' AND '2005';

-- 27
SELECT `IdLivre`, `IdExemplaire`, `IdPersonne`
FROM `BD101_EMPRUNTS`
WHERE `DateRetour` IS NULL;

-- 28
SELECT `Etat`, COUNT(IdExemplaire)
FROM `BD101_EXEMPLAIRES`
GROUP BY `Etat`;

-- 29
SELECT `Titre`, `BD101_AUTEURS`.`Nom`, `BD101_AUTEURS`.`Prenom`
FROM `BD101_LIVRES`
INNER JOIN `BD101_AUTEURS` USING(`IdAuteur`)
INNER JOIN `BD101_EMPRUNTS` USING (`IdLivre`)
GROUP BY `IdLivre`
HAVING COUNT(`IdLivre`) > 10;

-- 30