
-- 1
SELECT `NomGrotte`
FROM `BD101_GROTTES`;

-- 2
SELECT Ville
FROM `BD101_GROTTES`
WHERE `NomGrotte` = 'Altamira';

-- 3
SELECT NomSalle
FROM `BD101_GROTTES`
INNER JOIN `BD101_SALLES` USING (`IdGrotte`)
WHERE `IdGrotte` = 9 AND `TypeSalle` = 'salle';

-- 4
SELECT NomSalle, TypeSalle
FROM `BD101_SALLES`
WHERE `TypeSalle` != LOWER('salle');

-- 5
SELECT COUNT(IdGrotte) AS NbrGrotte
FROM `BD101_GROTTES`;

-- 6
SELECT NomSalle
FROM BD101_SALLES
WHERE NomSalle LIKE '%bison' OR NomSalle LIKE '%bisons';

-- 7
SELECT NomGrotte, COUNT(IdSalle)
FROM `BD101_GROTTES`
INNER JOIN `BD101_SALLES` USING (`IdGrotte`)
GROUP BY `IdGrotte`;

-- 8
SELECT NomGrotte
FROM `BD101_GROTTES`
WHERE `CommGrotte` LIKE '%versailles de la préhistoire%';

-- 9
SELECT MAX(quantite)
FROM `BD101_FIGURATIONS`;

-- 10
SELECT NomSalle
FROM `BD101_GROTTES`
INNER JOIN `BD101_SALLES` USING (`IdGrotte`)
WHERE `NomGrotte` = UPPER('LASCAUX');

-- 11
SELECT NomOeuvre
FROM `BD101_PERIODES`
INNER JOIN `BD101_OEUVRES` USING(`IdPeriode`)
WHERE `NomPeriode` = LOWER('Magdalénien');

-- 12
SELECT DISTINCT NomOeuvre
FROM `BD101_FIGURATIONS`
INNER JOIN `BD101_OEUVRES` USING(`IdOeuvre`)
WHERE NomOeuvre LIKE '%vache%' AND `quantite` > 2;

-- 13
SELECT NomOeuvre, NomSalle
FROM `BD101_SALLES`
INNER JOIN `BD101_OEUVRES` USING(`IdSalle`)
INNER JOIN `BD101_UTILISATIONS` ON BD101_OEUVRES.`IdOeuvre` = BD101_UTILISATIONS.`IdOeuvre`
INNER JOIN `BD101_MATERIAUX` ON BD101_UTILISATIONS.`IdMateriau` = BD101_MATERIAUX.`IdMateriau`
WHERE NomMateriau = LOWER('charbon de bois');

-- 14
SELECT NomGrotte
FROM `BD101_REGIONS`
INNER JOIN `BD101_GROTTES` USING(`IdRegion`)
WHERE `Pays` = LOWER('France')
ORDER BY `NomGrotte`;

-- 15
SELECT DISTINCT NomSujet, NomCategorie
FROM `BD101_GROTTES`
INNER JOIN `BD101_SALLES` USING (`IdGrotte`)
INNER JOIN `BD101_OEUVRES` ON BD101_SALLES.`IdSalle` = BD101_OEUVRES.`IdSalle`
INNER JOIN `BD101_FIGURATIONS` ON BD101_OEUVRES.`IdOeuvre` = BD101_FIGURATIONS.`IdOeuvre`
INNER JOIN `BD101_SUJETS` ON BD101_FIGURATIONS.`IdSujet` = BD101_SUJETS.`IdSujet`
INNER JOIN `BD101_CATEGORIES` ON BD101_SUJETS.`IdCategorie` = BD101_CATEGORIES.`IdCategorie`
WHERE `NomGrotte` = LOWER('Lascaux');

-- 16
SELECT NomOeuvre
FROM `BD101_OEUVRES`
WHERE `IdPeriode` IS NULL;

-- 17
SELECT DISTINCT `NomGrotte`
FROM `BD101_OEUVRES`
INNER JOIN `BD101_SALLES` ON BD101_OEUVRES.`IdSalle` = BD101_SALLES.IdSalle
INNER JOIN `BD101_GROTTES` ON BD101_SALLES.`IdGrotte` = BD101_GROTTES.`IdGrotte`
WHERE `IdPeriode` IS NULL;

-- 18
SELECT `NomRegion`, COUNT(`IdGrotte`)
FROM `BD101_REGIONS`
INNER JOIN `BD101_GROTTES` USING (`IdRegion`)
GROUP BY `IdRegion`;

-- 19
SELECT `NomGrotte`
FROM `BD101_GROTTES`
INNER JOIN `BD101_SALLES` USING (`IdGrotte`)
INNER JOIN `BD101_OEUVRES` ON BD101_SALLES.`IdSalle` = BD101_OEUVRES.`IdSalle`
INNER JOIN `BD101_FIGURATIONS` ON BD101_OEUVRES.`IdOeuvre` = BD101_FIGURATIONS.`IdOeuvre`
INNER JOIN `BD101_SUJETS` ON BD101_FIGURATIONS.`IdSujet` = BD101_SUJETS.`IdSujet`
GROUP BY `NomGrotte`
HAVING COUNT(`NomSujet`) > 5;

-- 20
SELECT NomOeuvre, Technique
FROM `BD101_OEUVRES`
INNER JOIN `BD101_FIGURATIONS` ON BD101_OEUVRES.`IdOeuvre` = BD101_FIGURATIONS.`IdOeuvre`
INNER JOIN `BD101_SUJETS` ON BD101_FIGURATIONS.`IdSujet` = BD101_SUJETS.`IdSujet`
INNER JOIN `BD101_CATEGORIES` ON BD101_SUJETS.`IdCategorie` = BD101_CATEGORIES.`IdCategorie`
WHERE `NomCategorie` = 'Faune'
ORDER BY `Technique`;

-- 21
SELECT `NomGrotte`, COUNT(`NomOeuvre`)
FROM `BD101_GROTTES`
INNER JOIN `BD101_SALLES` USING (`IdGrotte`)
INNER JOIN `BD101_OEUVRES` ON BD101_SALLES.`IdSalle` = BD101_OEUVRES.`IdSalle`
GROUP BY `NomGrotte`
HAVING COUNT(`NomOeuvre`) > 3;

-- 22
SELECT  `NomOeuvre`, `NomCategorie`, COUNT(`NomSujet`)
FROM `BD101_FIGURATIONS`
INNER JOIN `BD101_OEUVRES` USING(`IdOeuvre`)
INNER JOIN `BD101_SUJETS` USING(`IdSujet`)
INNER JOIN `BD101_CATEGORIES` ON BD101_SUJETS.`IdCategorie` = BD101_CATEGORIES.`IdCategorie`
GROUP BY `NomOeuvre`, `NomCategorie`
ORDER BY `NomOeuvre`;

-- 23
SELECT  `NomCategorie`
FROM `BD101_SUJETS`
INNER JOIN `BD101_CATEGORIES` USING(`IdCategorie`)
INNER JOIN `BD101_FIGURATIONS` USING (`IdSujet`)
INNER JOIN `BD101_OEUVRES` ON BD101_FIGURATIONS.`IdOeuvre` = `BD101_OEUVRES`.`IdOeuvre`
GROUP BY `IdCategorie`
HAVING COUNT(`IdSujet`) > 4;

-- 24
SELECT `NomGrotte`, NomSalle
FROM `BD101_GROTTES`
INNER JOIN `BD101_SALLES` USING(`IdGrotte`);

-- 25
SELECT DISTINCT NomSalle
FROM `BD101_SALLES`
INNER JOIN `BD101_COMMUNICATIONS` ON BD101_SALLES.`IdSalle` = BD101_COMMUNICATIONS.`IdSalleVers` OR BD101_SALLES.`IdSalle` = BD101_COMMUNICATIONS.`IdSalleVia`;

-- 26
SELECT COUNT(NomOeuvre)
FROM `BD101_OEUVRES`
WHERE `Technique` IS NULL;

-- 27
SELECT Orientation
FROM `BD101_OEUVRES`
GROUP BY `Orientation`
HAVING COUNT(`Orientation`) > 10;
-- FIN