
SELECT Prenom
FROM BD101_INDIVIDUS
WHERE SOUNDEX(Prenom) = SOUNDEX("Jaune");

SELECT COUNT(Nom) AS Nombre
FROM BD101_INDIVIDUS;

SELECT Titre AS Titre
FROM BD101_FILMS
INNER JOIN BD101_INDIVIDUS ON BD101_FILMS.NumInd = BD101_INDIVIDUS.NumInd
WHERE BD101_INDIVIDUS.NumInd = 13;

SELECT Titre AS Titre
FROM BD101_FILMS
INNER JOIN BD101_INDIVIDUS ON BD101_FILMS.NumInd = BD101_INDIVIDUS.NumInd
WHERE BD101_INDIVIDUS.Nom = "von Trier" AND BD101_INDIVIDUS.Prenom = "Lars" AND BD101_FILMS.Annee = 2002;

SELECT COUNT(Titre) AS Nombre
FROM BD101_FILMS
INNER JOIN BD101_INDIVIDUS ON BD101_FILMS.NumInd = BD101_INDIVIDUS.NumInd
WHERE BD101_INDIVIDUS.Nom = "Cronenberg" AND BD101_INDIVIDUS.Prenom = "David";

SELECT MAX(DateProj)
FROM BD101_PROJECTIONS

SELECT Titre
FROM BD101_FILMS
WHERE BD101_FILMS.Annee >= 1980 AND BD101_FILMS.Annee<= 2000;

SELECT DAYNAME(DateProj) AS Jours
FROM BD101_PROJECTIONS

SELECT DISTINCT Titre
FROM BD101_FILMS
INNER JOIN BD101_PROJECTIONS ON BD101_FILMS.NumFilm = BD101_PROJECTIONS.NumFilm
INNER JOIN BD101_CINEMAS ON BD101_PROJECTIONS.NumCine = BD101_CINEMAS.NumCine
WHERE BD101_CINEMAS.Nom = "Le Fontenelle"

SELECT Titre, Nom
FROM BD101_ACTEURS
INNER JOIN BD101_INDIVIDUS ON BD101_ACTEURS.NumInd = BD101_INDIVIDUS.NumInd
INNER JOIN BD101_FILMS ON BD101_ACTEURS.NumFilm = BD101_FILMS.NumFilm
WHERE BD101_ACTEURS.Role  IS NULL;

SELECT DISTINCT Titre
FROM BD101_ACTEURS
INNER JOIN BD101_INDIVIDUS ON BD101_ACTEURS.NumInd = BD101_INDIVIDUS.NumInd
INNER JOIN BD101_FILMS ON BD101_ACTEURS.NumFilm = BD101_FILMS.NumFilm
INNER JOIN BD101_PROJECTIONS ON BD101_ACTEURS.NumFilm = BD101_PROJECTIONS.NumFilm
INNER JOIN BD101_CINEMAS ON BD101_PROJECTIONS.NumCine = BD101_CINEMAS.NumCine
WHERE UPPER(BD101_INDIVIDUS.Nom) = "KIDMAN" AND BD101_ACTEURS.Role  IS NOT NULL AND UPPER(BD101_CINEMAS.Nom) = "LE FONTENELLE";

SELECT DateProj, Nom
FROM BD101_PROJECTIONS
INNER JOIN BD101_CINEMAS USING (NumCine)
INNER JOIN BD101_FILMS USING (NumFilm)
WHERE UPPER(BD101_FILMS.Titre) = "PULP FICTION";

SELECT Nom, Prenom, Role
FROM BD101_ACTEURS
INNER JOIN BD101_INDIVIDUS USING (NumInd)
INNER JOIN BD101_FILMS USING (NumFilm)
WHERE BD101_ACTEURS.Role IS NOT NULL AND UPPER(BD101_FILMS.Titre) = "BREAKING THE WAVES";

SELECT Nom, Prenom, COUNT(NumFilm)
FROM BD101_INDIVIDUS
INNER JOIN BD101_FILMS USING (NumInd)
GROUP BY BD101_INDIVIDUS.NumInd;

SELECT Nom, Prenom, COUNT(Titre)
FROM BD101_ACTEURS
INNER JOIN BD101_INDIVIDUS USING (NumInd)
INNER JOIN BD101_FILMS USING (NumFilm)
GROUP BY BD101_INDIVIDUS.NumInd
ORDER BY BD101_INDIVIDUS.Nom;

SELECT Nom, Prenom
FROM BD101_ACTEURS
INNER JOIN BD101_INDIVIDUS USING (NumInd)
INNER JOIN BD101_FILMS USING (NumFilm)
GROUP BY BD101_INDIVIDUS.NumInd
HAVING COUNT(BD101_FILMS.NumFilm) > 1
ORDER BY Nom;

# SELECT Titre, Nom, Prenom, COUNT(Nom)
# FROM BD101_ACTEURS
# INNER JOIN BD101_INDIVIDUS USING (NumInd)
# INNER JOIN BD101_FILMS USING (NumFilm)
# GROUP BY BD101_FILMS.NumFilm;