SET FOREIGN_KEY_CHECKS=0;
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


DROP TABLE IF EXISTS BD101_CATEGORIES;
CREATE TABLE IF NOT EXISTS BD101_CATEGORIES (
  IdCategorie int(2) NOT NULL,
  NomCategorie varchar(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_COMMUNICATIONS;
CREATE TABLE IF NOT EXISTS BD101_COMMUNICATIONS (
  IdSalleVia int(8) NOT NULL,
  IdSalleVers int(8) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_FIGURATIONS;
CREATE TABLE IF NOT EXISTS BD101_FIGURATIONS (
  IdOeuvre int(10) NOT NULL,
  IdSujet int(3) NOT NULL,
  Quantite int(2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_GROTTES;
CREATE TABLE IF NOT EXISTS BD101_GROTTES (
  IdGrotte int(5) NOT NULL,
  NomGrotte varchar(25) NOT NULL,
  CommGrotte varchar(500) DEFAULT NULL,
  DateDecouverte varchar(10) DEFAULT NULL,
  Plan varchar(50) DEFAULT NULL,
  PosGrotte varchar(30) DEFAULT NULL,
  Ville varchar(25) DEFAULT NULL,
  IdRegion int(3) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_MATERIAUX;
CREATE TABLE IF NOT EXISTS BD101_MATERIAUX (
  IdMateriau int(3) NOT NULL,
  NomMateriau varchar(25) NOT NULL,
  CommMateriau varchar(300) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_OEUVRES;
CREATE TABLE IF NOT EXISTS BD101_OEUVRES (
  IdOeuvre int(10) NOT NULL,
  NomOeuvre varchar(30) NOT NULL,
  LocOeuvre varchar(30) DEFAULT NULL,
  Technique varchar(25) DEFAULT NULL,
  Orientation varchar(25) DEFAULT NULL,
  DimOeuvre varchar(50) DEFAULT NULL,
  CommOeuvre varchar(300) DEFAULT NULL,
  IdSalle int(8) NOT NULL,
  IdPeriode int(2) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_PERIODES;
CREATE TABLE IF NOT EXISTS BD101_PERIODES (
  IdPeriode int(2) NOT NULL,
  NomPeriode varchar(25) NOT NULL,
  DatePeriode varchar(50) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_REGIONS;
CREATE TABLE IF NOT EXISTS BD101_REGIONS (
  IdRegion int(3) NOT NULL,
  NomRegion varchar(25) NOT NULL,
  Pays varchar(25) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_SALLES;
CREATE TABLE IF NOT EXISTS BD101_SALLES (
  IdSalle int(8) NOT NULL,
  NomSalle varchar(30) NOT NULL,
  TypeSalle varchar(25) DEFAULT NULL,
  PosSalle varchar(50) DEFAULT NULL,
  DimSalle varchar(50) DEFAULT NULL,
  IdGrotte int(5) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_SUJETS;
CREATE TABLE IF NOT EXISTS BD101_SUJETS (
  IdSujet int(3) NOT NULL,
  NomSujet varchar(25) NOT NULL,
  IdCategorie int(2) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_SUPERPOSITIONS;
CREATE TABLE IF NOT EXISTS BD101_SUPERPOSITIONS (
  IdOeuvreSur int(10) NOT NULL,
  IdOeuvreSous int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

DROP TABLE IF EXISTS BD101_UTILISATIONS;
CREATE TABLE IF NOT EXISTS BD101_UTILISATIONS (
  IdMateriau int(3) NOT NULL,
  IdOeuvre int(10) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


ALTER TABLE BD101_CATEGORIES
  ADD PRIMARY KEY (IdCategorie);

ALTER TABLE BD101_COMMUNICATIONS
  ADD PRIMARY KEY (IdSalleVia,IdSalleVers),
  ADD KEY IdSalleVers (IdSalleVers);

ALTER TABLE BD101_FIGURATIONS
  ADD PRIMARY KEY (IdOeuvre,IdSujet),
  ADD KEY IdSujet (IdSujet);

ALTER TABLE BD101_GROTTES
  ADD PRIMARY KEY (IdGrotte),
  ADD KEY IdRegion (IdRegion);

ALTER TABLE BD101_MATERIAUX
  ADD PRIMARY KEY (IdMateriau);

ALTER TABLE BD101_OEUVRES
  ADD PRIMARY KEY (IdOeuvre),
  ADD KEY IdSalle (IdSalle),
  ADD KEY IdPeriode (IdPeriode);

ALTER TABLE BD101_PERIODES
  ADD PRIMARY KEY (IdPeriode);

ALTER TABLE BD101_REGIONS
  ADD PRIMARY KEY (IdRegion);

ALTER TABLE BD101_SALLES
  ADD PRIMARY KEY (IdSalle),
  ADD KEY IdGrotte (IdGrotte);

ALTER TABLE BD101_SUJETS
  ADD PRIMARY KEY (IdSujet),
  ADD KEY IdCategorie (IdCategorie);

ALTER TABLE BD101_SUPERPOSITIONS
  ADD PRIMARY KEY (IdOeuvreSur,IdOeuvreSous),
  ADD KEY IdOeuvreSous (IdOeuvreSous);

ALTER TABLE BD101_UTILISATIONS
  ADD PRIMARY KEY (IdMateriau,IdOeuvre),
  ADD KEY IdOeuvre (IdOeuvre);


ALTER TABLE BD101_COMMUNICATIONS
  ADD CONSTRAINT BD101_COMMUNICATIONS_ibfk_1 FOREIGN KEY (IdSalleVia) REFERENCES BD101_SALLES (IdSalle),
  ADD CONSTRAINT BD101_COMMUNICATIONS_ibfk_2 FOREIGN KEY (IdSalleVers) REFERENCES BD101_SALLES (IdSalle);

ALTER TABLE BD101_FIGURATIONS
  ADD CONSTRAINT BD101_FIGURATIONS_ibfk_1 FOREIGN KEY (IdOeuvre) REFERENCES BD101_OEUVRES (IdOeuvre),
  ADD CONSTRAINT BD101_FIGURATIONS_ibfk_2 FOREIGN KEY (IdSujet) REFERENCES BD101_SUJETS (IdSujet);

ALTER TABLE BD101_GROTTES
  ADD CONSTRAINT BD101_GROTTES_ibfk_1 FOREIGN KEY (IdRegion) REFERENCES BD101_REGIONS (IdRegion);

ALTER TABLE BD101_OEUVRES
  ADD CONSTRAINT BD101_OEUVRES_ibfk_1 FOREIGN KEY (IdSalle) REFERENCES BD101_SALLES (IdSalle),
  ADD CONSTRAINT BD101_OEUVRES_ibfk_2 FOREIGN KEY (IdPeriode) REFERENCES BD101_PERIODES (IdPeriode);

ALTER TABLE BD101_SALLES
  ADD CONSTRAINT BD101_SALLES_ibfk_1 FOREIGN KEY (IdGrotte) REFERENCES BD101_GROTTES (IdGrotte);

ALTER TABLE BD101_SUJETS
  ADD CONSTRAINT BD101_SUJETS_ibfk_1 FOREIGN KEY (IdCategorie) REFERENCES BD101_CATEGORIES (IdCategorie);

ALTER TABLE BD101_SUPERPOSITIONS
  ADD CONSTRAINT BD101_SUPERPOSITIONS_ibfk_1 FOREIGN KEY (IdOeuvreSur) REFERENCES BD101_OEUVRES (IdOeuvre),
  ADD CONSTRAINT BD101_SUPERPOSITIONS_ibfk_2 FOREIGN KEY (IdOeuvreSous) REFERENCES BD101_OEUVRES (IdOeuvre);

ALTER TABLE BD101_UTILISATIONS
  ADD CONSTRAINT BD101_UTILISATIONS_ibfk_1 FOREIGN KEY (IdMateriau) REFERENCES BD101_MATERIAUX (IdMateriau),
  ADD CONSTRAINT BD101_UTILISATIONS_ibfk_2 FOREIGN KEY (IdOeuvre) REFERENCES BD101_OEUVRES (IdOeuvre);
SET FOREIGN_KEY_CHECKS=1;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
